# Generated by Django 6.0.4 on 2026-04-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
